name: CML
on: [pull_request]
jobs:
  report-metric-diff:
    runs-on: ubuntu-latest
    steps:
      - uses: iterative/setup-cml@v1
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: iterative/setup-dvc@v1
      - name: Evaluate model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |
          pip install -r requirements.txt
          dvc pull
          dvc repro evaluate
      - name: Create report
        run: |
          echo "# CML report" >> report.md
          git fetch --depth=1 origin main:main
          dvc metrics diff --show-md main >> report.md
          dvc plots show data/predictions/val.csv --template confusion -x actual -y prediction --show-vega > ./confusion.vega
          vl2png confusion.vega > confusion.png
          echo '![](./confusion.png "Confusion Matrix")' >> report.md
          cml comment create report.md
